language: python
sudo: false
python:
- '2.7'
install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget http://repo.continuum.io/miniconda/Miniconda-3.7.0-Linux-x86_64.sh
  -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- |
  conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION cytoolz numpy pandas pip pytables pyyaml toolz psutil
- source activate test-environment
- pip install orca openmatrix zbox
- pip install pytest pytest-cov coveralls pycodestyle pytest-xdist
- pip install sphinx numpydoc
- pip --no-cache-dir install https://github.com/RSGInc/activitysim/zipball/master
- pip install .
script:
- pycodestyle freightsim
- py.test --boxed --cov activitysim --cov-report term-missing
after_success:
- coveralls
notifications:
  slack:
    secure: HjHpcCU6WzHLzlieBhwkuWdt9Gj35xYRE89F9xczYqmGj1se/g7x6VcCPx8dYGYh1/GwSEjkQdilspDpxmtDVH4WjUialM10vh/q9kfvemXtMzXtFhajfBSlY/RQgjupD2JHoDvtlirlVzBWhEHMrkTe85Xk4iec6NG4qR9BJmEOgtdGMskPfJQHjkVqFYoECKMQCJf6rFNCDUWTHeCQ4fI/uDPKSj9lL79WZFNnk4taMXSCI6MtTSpzP7/Laa24m1Q+UeB95gSTGl7Z+6BnBJySuL9Jl47ltx/sxHkOdj3i/VHWOHSCq6V2QBDzHB1rJD892+Z/NqnWc7uwMtO3R/o9qc56YZRewD+zKHTgcdmgmMqREMqXdd3O+UGkCJ6dXny+pYtFqWRQqdLPxeTpdyFKaZC+3GXNxM+tlAqcFCSQG96LnG18ZI7vyEaTN/qQ1OE3V/vxGoHtB2zSJpTbfj8dUSEVoscNL3MzSDM2dJvzOmptImXXyvjb3IvOyaN9xHBNMnbltVaSgHyxL9r8M4pe3a8Rf9TBV/hOLWSn3sHjcEGj8AKdlEiTFjNCEIvTmK/u9YHPQEFMfnJ/MM0Fae5ewPeMTwy9BqDv3lwH+jdbGm3dZqIA7ryPkcRnZnYmpRIKUph5gJF2Svh2Pz4ihhUXz93H5+8yrf4x2fjjvRA=
#env:
#  global:
#  # GH_TOKEN
#  - secure: Lx7qJsqlshrmPWAZbYXOs0Pe0pvX1VyPuh22LPo8/7E7TqsMilps5U+0qp17Yg46CwzKgfnx+mrr0Emz2g7a2rj3VPeqsdSM2erOX/wuhKSOlqFNbzgD9CbuyaBdDdbLsuqrmOq8IZHWAOnHJoqn2L53rYl05mrN/PhZKN8M6O8=
